#Fichero Vagrant para crear y provisionar tres máquinas virtuales Ubuntu 14.04.

Vagrant.configure(2) do |config|

  #Definimos la configuración de las tres máquinas virtuales.
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/trusty64"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/trusty64"
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "ubuntu/trusty64"
  end

  #Especificamos cual será el fichero de ansible que va a provisionar las tres máquinas virtuales.

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
