FROM django
MAINTAINER Mario Ortega Aguayo "mortega87@gmail.com"

RUN apt-get update

#Install Git
RUN apt-get -y install git

#Download repository
RUN git clone https://github.com/mortega87/ProyectoCC-16-17


#Install MongoDB
RUN apt-get -y install mongodb

